<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>ToGetHer Manager Home</title>
</head>
<body>

<h1>Manager Home</h1>
	<form action="recordDate.jsp" method= "post">

	<button type="submit" formaction="MailingList" method="get">Customer Mailing Lists</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Obtain a sales report for a particular month</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Produce a comprehensive listing of all users</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Produce a list of dates by calendar date or by customer name</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Produce a summary listing of revenue generated by dates on a particular calendar date or involving a particular customer</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Determine which customer representative generated most total revenue</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Determine which customer generated most total revenue</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Produce a list of most active customers</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Produce a list of all customers who have dated a particular customer</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Produce a list of the highest-rated customers</button><br>
		<br>
		<button type="submit" formaction="MailingList" method="get">Produce a list of the highest-rated calendar dates to have a date on</button><br>
		<br>
		
</body>
</html>