<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>ToGetHer Manager Home</title>
</head>
<body>

<h1>Manager Home</h1>
	<form action="recordDate.jsp" method= "post">

	<button type="submit" formaction="SelectEmployeeServlet" method="get">Add, Edit, and Delete Employee Info</button><br>
		<br>
		<button type="submit" formaction="SaleReportServlet" method="get">Obtain a sales report for a particular month</button><br>
		<br>
		<button type="submit" formaction="ListAllUserServlet" method="get">Produce a comprehensive listing of all users</button><br>
		<br>
		<button type="submit" formaction="ListOfDateServlet" method="get">Produce a list of dates by calendar date </button><br>
		<br>
		<button type="submit" formaction="ListOfDateServlet2" method="get">Produce a list of dates by customer name</button><br>
		<br>
		<button type="submit" formaction="RevenueByDateServlet" method="get">Produce a summary listing of revenue generated by dates on a particular calendar date</button><br>
		<br>
		<button type="submit" formaction="RevenueByCusServlet" method="get">Produce a summary listing of revenue generated by involving a particular customer</button><br>
		<br>
		<button type="submit" formaction="BestCusRepServlet" method="get">Determine which customer representative generated most total revenue</button><br>
		<br>
		<button type="submit" formaction="BestCusServlet" method="get">Determine which customer generated most total revenue</button><br>
		<br>
		<button type="submit" formaction="MostActiveCusServlet" method="get">Produce a list of most active customers</button><br>
		<br>
		<button type="submit" formaction="DatedServlet" method="get">Produce a list of all customers who have dated a particular customer</button><br>
		<br>
		<button type="submit" formaction="HighRatedCusServlet" method="get">Produce a list of the highest-rated customers</button><br>
		<br>
		<button type="submit" formaction="HighRatedDateServlet" method="get">Produce a list of the highest-rated calendar dates to have a date on</button><br>
		<br>
		
</body>
</html>